# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/mono2dwidget.ui'
#
# Created: Tue Jul 28 09:59:25 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Mono2DWidget(object):
    def setupUi(self, Mono2DWidget):
        Mono2DWidget.setObjectName("Mono2DWidget")
        Mono2DWidget.resize(967, 637)
        self.gridLayout_2 = QtGui.QGridLayout(Mono2DWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widgetSceneviewerExperimental = MonoSceneviewerWidget(Mono2DWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widgetSceneviewerExperimental.sizePolicy().hasHeightForWidth())
        self.widgetSceneviewerExperimental.setSizePolicy(sizePolicy)
        self.widgetSceneviewerExperimental.setObjectName("widgetSceneviewerExperimental")
        self.gridLayout_2.addWidget(self.widgetSceneviewerExperimental, 0, 0, 1, 1)
        self.widgetSceneviewerConverged = MonoSceneviewerWidget(Mono2DWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widgetSceneviewerConverged.sizePolicy().hasHeightForWidth())
        self.widgetSceneviewerConverged.setSizePolicy(sizePolicy)
        self.widgetSceneviewerConverged.setObjectName("widgetSceneviewerConverged")
        self.gridLayout_2.addWidget(self.widgetSceneviewerConverged, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(Mono2DWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBoxXDiscretisation = QtGui.QSpinBox(self.groupBox)
        self.spinBoxXDiscretisation.setMinimum(1)
        self.spinBoxXDiscretisation.setMaximum(10)
        self.spinBoxXDiscretisation.setObjectName("spinBoxXDiscretisation")
        self.horizontalLayout.addWidget(self.spinBoxXDiscretisation)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBoxYDiscretisation = QtGui.QSpinBox(self.groupBox)
        self.spinBoxYDiscretisation.setMinimum(1)
        self.spinBoxYDiscretisation.setMaximum(10)
        self.spinBoxYDiscretisation.setObjectName("spinBoxYDiscretisation")
        self.horizontalLayout.addWidget(self.spinBoxYDiscretisation)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelStepSize = QtGui.QLabel(self.groupBox)
        self.labelStepSize.setObjectName("labelStepSize")
        self.horizontalLayout.addWidget(self.labelStepSize)
        self.doubleSpinBoxStepSize = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxStepSize.setDecimals(8)
        self.doubleSpinBoxStepSize.setMinimum(1e-06)
        self.doubleSpinBoxStepSize.setObjectName("doubleSpinBoxStepSize")
        self.horizontalLayout.addWidget(self.doubleSpinBoxStepSize)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonSimulate = QtGui.QPushButton(self.groupBox)
        self.pushButtonSimulate.setObjectName("pushButtonSimulate")
        self.horizontalLayout_3.addWidget(self.pushButtonSimulate)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButtonContinue = QtGui.QPushButton(self.groupBox)
        self.pushButtonContinue.setObjectName("pushButtonContinue")
        self.horizontalLayout_4.addWidget(self.pushButtonContinue)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.labelTime = QtGui.QLabel(self.groupBox)
        self.labelTime.setText("")
        self.labelTime.setObjectName("labelTime")
        self.horizontalLayout_5.addWidget(self.labelTime)
        self.horizontalSliderTime = QtGui.QSlider(self.groupBox)
        self.horizontalSliderTime.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTime.setObjectName("horizontalSliderTime")
        self.horizontalLayout_5.addWidget(self.horizontalSliderTime)
        self.pushButtonPlayStop = QtGui.QPushButton(self.groupBox)
        self.pushButtonPlayStop.setObjectName("pushButtonPlayStop")
        self.horizontalLayout_5.addWidget(self.pushButtonPlayStop)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 2)

        self.retranslateUi(Mono2DWidget)
        QtCore.QMetaObject.connectSlotsByName(Mono2DWidget)

    def retranslateUi(self, Mono2DWidget):
        Mono2DWidget.setWindowTitle(QtGui.QApplication.translate("Mono2DWidget", "Monodomain 2D", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Mono2DWidget", "Monodomain Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Mono2DWidget", "Discretisation x = ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Mono2DWidget", "y = ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStepSize.setText(QtGui.QApplication.translate("Mono2DWidget", "Step size:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSimulate.setText(QtGui.QApplication.translate("Mono2DWidget", "Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonContinue.setText(QtGui.QApplication.translate("Mono2DWidget", "Continue", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Mono2DWidget", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPlayStop.setText(QtGui.QApplication.translate("Mono2DWidget", "Play", None, QtGui.QApplication.UnicodeUTF8))

from monosceneviewerwidget import MonoSceneviewerWidget
